2018-04-03 15:29:12.296000 Launched python -u C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py
2018-04-03 15:29:12.361000 Main run...
2018-04-03 15:29:12.373000 
2018-04-03 15:29:12.434000 Starting threads...
2018-04-03 15:29:12.450000 try write
2018-04-03 15:29:12.461000 write ok
2018-04-03 15:29:12.475000 Init error
2018-04-03 15:29:22.890000 received: $PUI12,77,15.1,
2018-04-03 15:29:22.902000 
2018-04-03 15:29:22.912000 Wheel to: 15.1
2018-04-03 15:29:22.922000 Traceback (most recent call last):
2018-04-03 15:29:22.930000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 414, in <module>
2018-04-03 15:29:22.938000 while ser.inWaiting():
2018-04-03 15:29:22.946000 AttributeError: 'str' object has no attribute 'inWaiting'
2018-04-03 15:29:23.088000 Process Process-2:
2018-04-03 15:29:23.096000 srv_interpreter_thread start
2018-04-03 15:29:23.104000 
2018-04-03 15:29:23.114000 Accepted new connection
2018-04-03 15:29:23.123000 cmdAgent runCmd by interpreter: $PUI12,77,15.1,
2018-04-03 15:29:23.132000 
2018-04-03 15:29:23.140000 Traceback (most recent call last):
2018-04-03 15:29:23.150000 File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
2018-04-03 15:29:23.159000 self.run()
2018-04-03 15:29:23.171000 File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
2018-04-03 15:29:23.182000 self._target(*self._args, **self._kwargs)
2018-04-03 15:29:23.190000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 170, in srv_interpreter_thread
2018-04-03 15:29:23.199000 while cmdAgent.hasData() and (flagStopThread.value == 0):
2018-04-03 15:29:23.208000 File "<string>", line 2, in hasData
2018-04-03 15:29:23.219000 File "C:\Python27\lib\multiprocessing\managers.py", line 758, in _callmethod
2018-04-03 15:29:23.229000 conn.send((self._id, methodname, args, kwds))
2018-04-03 15:29:23.240000 IOError: [Errno 232] The pipe is being closed
2018-04-03 15:29:23.252000 Launcher terminating...
2018-04-03 15:33:48.879000 Launched python -u C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py
2018-04-03 15:33:48.940000 Main run...
2018-04-03 15:33:48.947000 
2018-04-03 15:33:49.025000 Starting threads...
2018-04-03 15:33:49.034000 try write
2018-04-03 15:33:49.042000 write ok
2018-04-03 15:33:49.049000 Init error
2018-04-03 15:33:52.557000 received: $PUI12,77,15.1,
2018-04-03 15:33:52.565000 
2018-04-03 15:33:52.572000 Wheel to: 15.1
2018-04-03 15:33:52.580000 Traceback (most recent call last):
2018-04-03 15:33:52.587000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 415, in <module>
2018-04-03 15:33:52.594000 while ser.inWaiting():
2018-04-03 15:33:52.600000 AttributeError: 'str' object has no attribute 'inWaiting'
2018-04-03 15:33:52.737000 Process Process-2:
2018-04-03 15:33:52.744000 srv_interpreter_thread start
2018-04-03 15:33:52.748000 
2018-04-03 15:33:52.753000 Accepted new connection
2018-04-03 15:33:52.758000 cmdAgent runCmd by interpreter: $PUI12,77,15.1,
2018-04-03 15:33:52.763000 
2018-04-03 15:33:52.792000 Traceback (most recent call last):
2018-04-03 15:33:52.797000 File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
2018-04-03 15:33:52.802000 self.run()
2018-04-03 15:33:52.807000 File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
2018-04-03 15:33:52.812000 self._target(*self._args, **self._kwargs)
2018-04-03 15:33:52.817000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 170, in srv_interpreter_thread
2018-04-03 15:33:52.822000 while cmdAgent.hasData() and (flagStopThread.value == 0):
2018-04-03 15:33:52.827000 File "<string>", line 2, in hasData
2018-04-03 15:33:52.832000 File "C:\Python27\lib\multiprocessing\managers.py", line 758, in _callmethod
2018-04-03 15:33:52.837000 conn.send((self._id, methodname, args, kwds))
2018-04-03 15:33:52.842000 IOError: [Errno 232] The pipe is being closed
2018-04-03 15:33:52.849000 Launcher terminating...
2018-04-03 16:07:32.811000 Launched python -u C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py
2018-04-03 16:07:32.872000 Main run...
2018-04-03 16:07:32.879000 
2018-04-03 16:07:32.946000 Starting threads...
2018-04-03 16:07:32.956000 try write
2018-04-03 16:07:32.970000 write ok
2018-04-03 16:07:32.977000 Init error
2018-04-03 16:07:37.086000 received: $PUI12,77,15.1,
2018-04-03 16:07:37.093000 
2018-04-03 16:07:37.099000 Wheel to: 15.1
2018-04-03 16:07:37.105000 Traceback (most recent call last):
2018-04-03 16:07:37.110000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 415, in <module>
2018-04-03 16:07:37.116000 while ser.inWaiting():
2018-04-03 16:07:37.123000 AttributeError: 'str' object has no attribute 'inWaiting'
2018-04-03 16:07:37.265000 Process Process-2:
2018-04-03 16:07:37.272000 srv_interpreter_thread start
2018-04-03 16:07:37.279000 
2018-04-03 16:07:37.285000 Accepted new connection
2018-04-03 16:07:37.290000 cmdAgent runCmd by interpreter: $PUI12,77,15.1,
2018-04-03 16:07:37.297000 
2018-04-03 16:07:37.302000 Traceback (most recent call last):
2018-04-03 16:07:37.307000 File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
2018-04-03 16:07:37.312000 self.run()
2018-04-03 16:07:37.317000 File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
2018-04-03 16:07:37.322000 self._target(*self._args, **self._kwargs)
2018-04-03 16:07:37.328000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 170, in srv_interpreter_thread
2018-04-03 16:07:37.333000 while cmdAgent.hasData() and (flagStopThread.value == 0):
2018-04-03 16:07:37.338000 File "<string>", line 2, in hasData
2018-04-03 16:07:37.343000 File "C:\Python27\lib\multiprocessing\managers.py", line 758, in _callmethod
2018-04-03 16:07:37.348000 conn.send((self._id, methodname, args, kwds))
2018-04-03 16:07:37.354000 IOError: [Errno 232] The pipe is being closed
2018-04-03 16:07:37.360000 Launcher terminating...
2018-04-03 16:08:45.353000 Launched python -u C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py
2018-04-03 16:08:45.416000 Main run...
2018-04-03 16:08:45.423000 
2018-04-03 16:08:45.487000 Starting threads...
2018-04-03 16:08:45.497000 try write
2018-04-03 16:08:45.511000 write ok
2018-04-03 16:08:45.520000 Init error
2018-04-03 16:08:49.326000 received: $PUI12,77,15.1,
2018-04-03 16:08:49.337000 
2018-04-03 16:08:49.349000 Wheel to: 15.1
2018-04-03 16:08:49.357000 Traceback (most recent call last):
2018-04-03 16:08:49.363000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 415, in <module>
2018-04-03 16:08:49.368000 while ser.inWaiting():
2018-04-03 16:08:49.373000 AttributeError: 'str' object has no attribute 'inWaiting'
2018-04-03 16:08:49.500000 Process Process-2:
2018-04-03 16:08:49.522000 srv_interpreter_thread start
2018-04-03 16:08:49.538000 
2018-04-03 16:08:49.548000 Accepted new connection
2018-04-03 16:08:49.558000 cmdAgent runCmd by interpreter: $PUI12,77,15.1,
2018-04-03 16:08:49.569000 
2018-04-03 16:08:49.574000 Traceback (most recent call last):
2018-04-03 16:08:49.580000 File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
2018-04-03 16:08:49.585000 self.run()
2018-04-03 16:08:49.591000 File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
2018-04-03 16:08:49.598000 self._target(*self._args, **self._kwargs)
2018-04-03 16:08:49.603000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 170, in srv_interpreter_thread
2018-04-03 16:08:49.609000 while cmdAgent.hasData() and (flagStopThread.value == 0):
2018-04-03 16:08:49.615000 File "<string>", line 2, in hasData
2018-04-03 16:08:49.620000 File "C:\Python27\lib\multiprocessing\managers.py", line 758, in _callmethod
2018-04-03 16:08:49.626000 conn.send((self._id, methodname, args, kwds))
2018-04-03 16:08:49.631000 IOError: [Errno 232] The pipe is being closed
2018-04-03 16:08:49.637000 Launcher terminating...
2018-04-03 16:10:15.492000 Launched python -u C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py
2018-04-03 16:10:15.553000 Main run...
2018-04-03 16:10:15.562000 
2018-04-03 16:10:15.626000 Starting threads...
2018-04-03 16:10:15.642000 try write
2018-04-03 16:10:15.653000 write ok
2018-04-03 16:10:15.661000 Init error
2018-04-03 16:10:20.571000 received: $PUI12,77,15.1,
2018-04-03 16:10:20.593000 
2018-04-03 16:10:20.609000 Wheel to: 15.1
2018-04-03 16:10:20.622000 Traceback (most recent call last):
2018-04-03 16:10:20.633000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 415, in <module>
2018-04-03 16:10:20.644000 while ser.inWaiting():
2018-04-03 16:10:20.652000 AttributeError: 'str' object has no attribute 'inWaiting'
2018-04-03 16:10:20.726000 Process Process-4:
2018-04-03 16:10:20.735000 Traceback (most recent call last):
2018-04-03 16:10:20.741000 File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
2018-04-03 16:10:20.746000 self.run()
2018-04-03 16:10:20.752000 File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
2018-04-03 16:10:20.758000 self._target(*self._args, **self._kwargs)
2018-04-03 16:10:20.763000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 75, in ip_autoconf_sender
2018-04-03 16:10:20.769000 missionEditorIp.incTime()
2018-04-03 16:10:20.775000 File "<string>", line 2, in incTime
2018-04-03 16:10:20.781000 File "C:\Python27\lib\multiprocessing\managers.py", line 758, in _callmethod
2018-04-03 16:10:20.786000 conn.send((self._id, methodname, args, kwds))
2018-04-03 16:10:20.792000 IOError: [Errno 232] The pipe is being closed
2018-04-03 16:10:20.799000 Launcher terminating...
2018-04-03 16:11:53.905000 Launched python -u C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py
2018-04-03 16:11:53.971000 Main run...
2018-04-03 16:11:53.980000 
2018-04-03 16:11:54.044000 Starting threads...
2018-04-03 16:11:54.055000 try write
2018-04-03 16:11:54.067000 write ok
2018-04-03 16:11:54.076000 Init error
2018-04-03 16:11:55.167000 received: $PUI12,77,15.1,
2018-04-03 16:11:55.184000 
2018-04-03 16:11:55.191000 Wheel to: 15.1
2018-04-03 16:11:55.199000 Traceback (most recent call last):
2018-04-03 16:11:55.207000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 415, in <module>
2018-04-03 16:11:55.215000 while ser.inWaiting():
2018-04-03 16:11:55.224000 AttributeError: 'str' object has no attribute 'inWaiting'
2018-04-03 16:11:55.355000 Process Process-2:
2018-04-03 16:11:55.362000 srv_interpreter_thread start
2018-04-03 16:11:55.367000 
2018-04-03 16:11:55.373000 Accepted new connection
2018-04-03 16:11:55.378000 cmdAgent runCmd by interpreter: $PUI12,77,15.1,
2018-04-03 16:11:55.383000 
2018-04-03 16:11:55.389000 Traceback (most recent call last):
2018-04-03 16:11:55.394000 File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
2018-04-03 16:11:55.399000 self.run()
2018-04-03 16:11:55.405000 File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
2018-04-03 16:11:55.410000 self._target(*self._args, **self._kwargs)
2018-04-03 16:11:55.416000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 170, in srv_interpreter_thread
2018-04-03 16:11:55.423000 while cmdAgent.hasData() and (flagStopThread.value == 0):
2018-04-03 16:11:55.428000 File "<string>", line 2, in hasData
2018-04-03 16:11:55.434000 File "C:\Python27\lib\multiprocessing\managers.py", line 758, in _callmethod
2018-04-03 16:11:55.439000 conn.send((self._id, methodname, args, kwds))
2018-04-03 16:11:55.445000 IOError: [Errno 232] The pipe is being closed
2018-04-03 16:11:55.451000 Launcher terminating...
2018-04-03 16:13:30.926000 Launched python -u C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py
2018-04-03 16:13:30.986000 Main run...
2018-04-03 16:13:30.993000 
2018-04-03 16:13:31.062000 Starting threads...
2018-04-03 16:13:31.077000 try write
2018-04-03 16:13:31.087000 write ok
2018-04-03 16:13:31.095000 Init error
2018-04-03 16:13:33.892000 received: $PUI12,77,15.1,
2018-04-03 16:13:33.902000 
2018-04-03 16:13:33.913000 Wheel to: 15.1
2018-04-03 16:13:33.923000 Traceback (most recent call last):
2018-04-03 16:13:33.932000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 415, in <module>
2018-04-03 16:13:33.941000 while ser.inWaiting():
2018-04-03 16:13:33.946000 AttributeError: 'str' object has no attribute 'inWaiting'
2018-04-03 16:13:34.075000 Process Process-2:
2018-04-03 16:13:34.097000 srv_interpreter_thread start
2018-04-03 16:13:34.115000 
2018-04-03 16:13:34.134000 Accepted new connection
2018-04-03 16:13:34.155000 cmdAgent runCmd by interpreter: $PUI12,77,15.1,
2018-04-03 16:13:34.176000 
2018-04-03 16:13:34.189000 Traceback (most recent call last):
2018-04-03 16:13:34.200000 File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
2018-04-03 16:13:34.210000 self.run()
2018-04-03 16:13:34.216000 File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
2018-04-03 16:13:34.222000 self._target(*self._args, **self._kwargs)
2018-04-03 16:13:34.227000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 170, in srv_interpreter_thread
2018-04-03 16:13:34.233000 while cmdAgent.hasData() and (flagStopThread.value == 0):
2018-04-03 16:13:34.241000 File "<string>", line 2, in hasData
2018-04-03 16:13:34.247000 File "C:\Python27\lib\multiprocessing\managers.py", line 758, in _callmethod
2018-04-03 16:13:34.252000 conn.send((self._id, methodname, args, kwds))
2018-04-03 16:13:34.258000 IOError: [Errno 232] The pipe is being closed
2018-04-03 16:13:34.266000 Launcher terminating...
2018-04-03 16:14:22.433000 Launched python -u C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py
2018-04-03 16:14:22.492000 Main run...
2018-04-03 16:14:22.500000 
2018-04-03 16:14:22.568000 Starting threads...
2018-04-03 16:14:22.581000 try write
2018-04-03 16:14:22.593000 write ok
2018-04-03 16:14:22.611000 Init error
2018-04-03 16:14:25.296000 received: $PUI12,77,15.1,
2018-04-03 16:14:25.323000 
2018-04-03 16:14:25.334000 Wheel to: 15.1
2018-04-03 16:14:25.340000 Traceback (most recent call last):
2018-04-03 16:14:25.346000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 415, in <module>
2018-04-03 16:14:25.352000 while ser.inWaiting():
2018-04-03 16:14:25.358000 AttributeError: 'str' object has no attribute 'inWaiting'
2018-04-03 16:14:25.413000 Process Process-2:
2018-04-03 16:14:25.421000 srv_interpreter_thread start
2018-04-03 16:14:25.427000 
2018-04-03 16:14:25.433000 Accepted new connection
2018-04-03 16:14:25.439000 cmdAgent runCmd by interpreter: $PUI12,77,15.1,
2018-04-03 16:14:25.445000 
2018-04-03 16:14:25.450000 Traceback (most recent call last):
2018-04-03 16:14:25.456000 File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
2018-04-03 16:14:25.462000 self.run()
2018-04-03 16:14:25.468000 File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
2018-04-03 16:14:25.473000 self._target(*self._args, **self._kwargs)
2018-04-03 16:14:25.479000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 170, in srv_interpreter_thread
2018-04-03 16:14:25.485000 while cmdAgent.hasData() and (flagStopThread.value == 0):
2018-04-03 16:14:25.491000 File "<string>", line 2, in hasData
2018-04-03 16:14:25.496000 File "C:\Python27\lib\multiprocessing\managers.py", line 758, in _callmethod
2018-04-03 16:14:25.502000 conn.send((self._id, methodname, args, kwds))
2018-04-03 16:14:25.507000 IOError: [Errno 232] The pipe is being closed
2018-04-03 16:14:25.678000 Process Process-4:
2018-04-03 16:14:25.700000 Traceback (most recent call last):
2018-04-03 16:14:25.719000 File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
2018-04-03 16:14:25.731000 self.run()
2018-04-03 16:14:25.747000 File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
2018-04-03 16:14:25.754000 self._target(*self._args, **self._kwargs)
2018-04-03 16:14:25.760000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 75, in ip_autoconf_sender
2018-04-03 16:14:25.766000 missionEditorIp.incTime()
2018-04-03 16:14:25.772000 File "<string>", line 2, in incTime
2018-04-03 16:14:25.778000 File "C:\Python27\lib\multiprocessing\managers.py", line 758, in _callmethod
2018-04-03 16:14:25.784000 conn.send((self._id, methodname, args, kwds))
2018-04-03 16:14:25.790000 IOError: [Errno 232] The pipe is being closed
2018-04-03 16:15:37.014000 Launcher terminating...
2018-04-03 16:15:39.510000 Launched python -u C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py
2018-04-03 16:15:39.577000 Main run...
2018-04-03 16:15:39.585000 
2018-04-03 16:15:39.656000 Starting threads...
2018-04-03 16:15:39.666000 try write
2018-04-03 16:15:39.676000 write ok
2018-04-03 16:15:39.685000 Init error
2018-04-03 16:15:42.077000 received: $PUI12,77,15.1,
2018-04-03 16:15:42.084000 
2018-04-03 16:15:42.089000 Wheel to: 15.1
2018-04-03 16:15:42.096000 Traceback (most recent call last):
2018-04-03 16:15:42.101000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 415, in <module>
2018-04-03 16:15:42.106000 while ser.inWaiting():
2018-04-03 16:15:42.112000 AttributeError: 'str' object has no attribute 'inWaiting'
2018-04-03 16:15:42.271000 Process Process-2:
2018-04-03 16:15:42.278000 srv_interpreter_thread start
2018-04-03 16:15:42.290000 
2018-04-03 16:15:42.308000 Accepted new connection
2018-04-03 16:15:42.316000 cmdAgent runCmd by interpreter: $PUI12,77,15.1,
2018-04-03 16:15:42.323000 
2018-04-03 16:15:42.330000 Traceback (most recent call last):
2018-04-03 16:15:42.337000 File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
2018-04-03 16:15:42.345000 self.run()
2018-04-03 16:15:42.352000 File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
2018-04-03 16:15:42.358000 self._target(*self._args, **self._kwargs)
2018-04-03 16:15:42.365000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 170, in srv_interpreter_thread
2018-04-03 16:15:42.372000 while cmdAgent.hasData() and (flagStopThread.value == 0):
2018-04-03 16:15:42.378000 File "<string>", line 2, in hasData
2018-04-03 16:15:42.384000 File "C:\Python27\lib\multiprocessing\managers.py", line 758, in _callmethod
2018-04-03 16:15:42.390000 conn.send((self._id, methodname, args, kwds))
2018-04-03 16:15:42.396000 IOError: [Errno 232] The pipe is being closed
2018-04-03 16:15:42.403000 Process terminated with exit code 1
2018-04-03 16:15:42.411000 Launched python -u C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py
2018-04-03 16:15:42.471000 Main run...
2018-04-03 16:15:42.478000 
2018-04-03 16:15:42.547000 Starting threads...
2018-04-03 16:15:42.561000 try write
2018-04-03 16:15:42.572000 write ok
2018-04-03 16:15:42.582000 Init error
2018-04-03 16:16:01.956000 received: $PUI12,77,15.1,
2018-04-03 16:16:01.973000 
2018-04-03 16:16:01.986000 Wheel to: 15.1
2018-04-03 16:16:01.993000 Traceback (most recent call last):
2018-04-03 16:16:01.999000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 415, in <module>
2018-04-03 16:16:02.005000 while ser.inWaiting():
2018-04-03 16:16:02.011000 AttributeError: 'str' object has no attribute 'inWaiting'
2018-04-03 16:16:02.150000 Process Process-2:
2018-04-03 16:16:02.173000 srv_interpreter_thread start
2018-04-03 16:16:02.183000 
2018-04-03 16:16:02.194000 Accepted new connection
2018-04-03 16:16:02.206000 cmdAgent runCmd by interpreter: $PUI12,77,15.1,
2018-04-03 16:16:02.217000 
2018-04-03 16:16:02.228000 Traceback (most recent call last):
2018-04-03 16:16:02.240000 File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
2018-04-03 16:16:02.251000 self.run()
2018-04-03 16:16:02.266000 File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
2018-04-03 16:16:02.277000 self._target(*self._args, **self._kwargs)
2018-04-03 16:16:02.290000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 170, in srv_interpreter_thread
2018-04-03 16:16:02.305000 while cmdAgent.hasData() and (flagStopThread.value == 0):
2018-04-03 16:16:02.318000 File "<string>", line 2, in hasData
2018-04-03 16:16:02.331000 File "C:\Python27\lib\multiprocessing\managers.py", line 758, in _callmethod
2018-04-03 16:16:02.344000 conn.send((self._id, methodname, args, kwds))
2018-04-03 16:16:02.353000 IOError: [Errno 232] The pipe is being closed
2018-04-03 16:16:02.364000 Process terminated with exit code 1
2018-04-03 16:16:02.373000 Launched python -u C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py
2018-04-03 16:16:02.434000 Main run...
2018-04-03 16:16:02.444000 
2018-04-03 16:16:02.513000 Starting threads...
2018-04-03 16:16:02.527000 try write
2018-04-03 16:16:02.539000 write ok
2018-04-03 16:16:02.550000 Init error
2018-04-03 16:16:05.944000 received: $PUI12,77,15.1,
2018-04-03 16:16:05.963000 
2018-04-03 16:16:05.980000 Wheel to: 15.1
2018-04-03 16:16:05.994000 Traceback (most recent call last):
2018-04-03 16:16:06.006000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 415, in <module>
2018-04-03 16:16:06.014000 while ser.inWaiting():
2018-04-03 16:16:06.019000 AttributeError: 'str' object has no attribute 'inWaiting'
2018-04-03 16:16:06.130000 Process Process-2:
2018-04-03 16:16:06.160000 srv_interpreter_thread start
2018-04-03 16:16:06.167000 
2018-04-03 16:16:06.173000 Accepted new connection
2018-04-03 16:16:06.179000 cmdAgent runCmd by interpreter: $PUI12,77,15.1,
2018-04-03 16:16:06.185000 
2018-04-03 16:16:06.192000 Traceback (most recent call last):
2018-04-03 16:16:06.198000 File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
2018-04-03 16:16:06.205000 self.run()
2018-04-03 16:16:06.211000 File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
2018-04-03 16:16:06.217000 self._target(*self._args, **self._kwargs)
2018-04-03 16:16:06.223000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 170, in srv_interpreter_thread
2018-04-03 16:16:06.229000 while cmdAgent.hasData() and (flagStopThread.value == 0):
2018-04-03 16:16:06.235000 File "<string>", line 2, in hasData
2018-04-03 16:16:06.241000 File "C:\Python27\lib\multiprocessing\managers.py", line 758, in _callmethod
2018-04-03 16:16:06.247000 conn.send((self._id, methodname, args, kwds))
2018-04-03 16:16:06.253000 IOError: [Errno 232] The pipe is being closed
2018-04-03 16:16:06.260000 Process terminated with exit code 1
2018-04-03 16:16:06.267000 Launched python -u C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py
2018-04-03 16:16:06.332000 Main run...
2018-04-03 16:16:06.341000 
2018-04-03 16:16:06.419000 Starting threads...
2018-04-03 16:16:06.433000 try write
2018-04-03 16:16:06.450000 write ok
2018-04-03 16:16:06.461000 Init error
2018-04-03 16:16:10.153000 received: $PUI12,77,15.1,
2018-04-03 16:16:10.180000 
2018-04-03 16:16:10.187000 Wheel to: 15.1
2018-04-03 16:16:10.194000 Traceback (most recent call last):
2018-04-03 16:16:10.200000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 415, in <module>
2018-04-03 16:16:10.207000 while ser.inWaiting():
2018-04-03 16:16:10.213000 AttributeError: 'str' object has no attribute 'inWaiting'
2018-04-03 16:16:10.345000 Process Process-2:
2018-04-03 16:16:10.364000 srv_interpreter_thread start
2018-04-03 16:16:10.375000 
2018-04-03 16:16:10.385000 Accepted new connection
2018-04-03 16:16:10.393000 cmdAgent runCmd by interpreter: $PUI12,77,15.1,
2018-04-03 16:16:10.401000 
2018-04-03 16:16:10.409000 Traceback (most recent call last):
2018-04-03 16:16:10.416000 File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
2018-04-03 16:16:10.424000 self.run()
2018-04-03 16:16:10.430000 File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
2018-04-03 16:16:10.438000 self._target(*self._args, **self._kwargs)
2018-04-03 16:16:10.446000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 170, in srv_interpreter_thread
2018-04-03 16:16:10.454000 while cmdAgent.hasData() and (flagStopThread.value == 0):
2018-04-03 16:16:10.462000 File "<string>", line 2, in hasData
2018-04-03 16:16:10.470000 File "C:\Python27\lib\multiprocessing\managers.py", line 758, in _callmethod
2018-04-03 16:16:10.477000 conn.send((self._id, methodname, args, kwds))
2018-04-03 16:16:10.485000 IOError: [Errno 232] The pipe is being closed
2018-04-03 16:16:10.494000 Process terminated with exit code 1
2018-04-03 16:16:10.502000 Launched python -u C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py
2018-04-03 16:16:10.561000 Main run...
2018-04-03 16:16:10.572000 
2018-04-03 16:16:10.638000 Starting threads...
2018-04-03 16:16:10.650000 try write
2018-04-03 16:16:10.665000 write ok
2018-04-03 16:16:10.678000 Init error
2018-04-03 16:16:14.068000 received: $PUI12,77,15.1,
2018-04-03 16:16:14.095000 
2018-04-03 16:16:14.113000 Wheel to: 15.1
2018-04-03 16:16:14.124000 Traceback (most recent call last):
2018-04-03 16:16:14.137000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 415, in <module>
2018-04-03 16:16:14.151000 while ser.inWaiting():
2018-04-03 16:16:14.164000 AttributeError: 'str' object has no attribute 'inWaiting'
2018-04-03 16:16:14.258000 Process Process-2:
2018-04-03 16:16:14.281000 srv_interpreter_thread start
2018-04-03 16:16:14.300000 
2018-04-03 16:16:14.319000 Accepted new connection
2018-04-03 16:16:14.333000 cmdAgent runCmd by interpreter: $PUI12,77,15.1,
2018-04-03 16:16:14.346000 
2018-04-03 16:16:14.354000 Traceback (most recent call last):
2018-04-03 16:16:14.360000 File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
2018-04-03 16:16:14.366000 self.run()
2018-04-03 16:16:14.373000 File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
2018-04-03 16:16:14.378000 self._target(*self._args, **self._kwargs)
2018-04-03 16:16:14.384000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 170, in srv_interpreter_thread
2018-04-03 16:16:14.390000 while cmdAgent.hasData() and (flagStopThread.value == 0):
2018-04-03 16:16:14.395000 File "<string>", line 2, in hasData
2018-04-03 16:16:14.400000 File "C:\Python27\lib\multiprocessing\managers.py", line 758, in _callmethod
2018-04-03 16:16:14.406000 conn.send((self._id, methodname, args, kwds))
2018-04-03 16:16:14.412000 IOError: [Errno 232] The pipe is being closed
2018-04-03 16:16:14.418000 Process terminated with exit code 1
2018-04-03 16:16:14.425000 Launched python -u C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py
2018-04-03 16:16:14.485000 Main run...
2018-04-03 16:16:14.493000 
2018-04-03 16:16:14.561000 Starting threads...
2018-04-03 16:16:14.575000 try write
2018-04-03 16:16:14.584000 write ok
2018-04-03 16:16:14.594000 Init error
2018-04-03 16:16:29.381000 Launcher terminating...
2018-04-03 16:18:00.271000 Launched python -u C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py
2018-04-03 16:18:00.334000 Main run...
2018-04-03 16:18:00.343000 
2018-04-03 16:18:00.412000 Starting threads...
2018-04-03 16:18:00.425000 try write
2018-04-03 16:18:00.438000 write ok
2018-04-03 16:18:00.447000 Init error
2018-04-03 16:18:03.542000 received: $PUI12,77,15.1,
2018-04-03 16:18:03.562000 
2018-04-03 16:18:03.578000 Wheel to: 15.1
2018-04-03 16:18:03.588000 Traceback (most recent call last):
2018-04-03 16:18:03.597000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 415, in <module>
2018-04-03 16:18:03.606000 while ser.inWaiting():
2018-04-03 16:18:03.613000 AttributeError: 'str' object has no attribute 'inWaiting'
2018-04-03 16:18:03.726000 Process Process-2:
2018-04-03 16:18:03.735000 srv_interpreter_thread start
2018-04-03 16:18:03.743000 
2018-04-03 16:18:03.749000 Accepted new connection
2018-04-03 16:18:03.755000 cmdAgent runCmd by interpreter: $PUI12,77,15.1,
2018-04-03 16:18:03.762000 
2018-04-03 16:18:03.767000 Traceback (most recent call last):
2018-04-03 16:18:03.774000 File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
2018-04-03 16:18:03.782000 self.run()
2018-04-03 16:18:03.791000 File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
2018-04-03 16:18:03.797000 self._target(*self._args, **self._kwargs)
2018-04-03 16:18:03.804000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 170, in srv_interpreter_thread
2018-04-03 16:18:03.810000 while cmdAgent.hasData() and (flagStopThread.value == 0):
2018-04-03 16:18:03.816000 File "<string>", line 2, in hasData
2018-04-03 16:18:03.824000 File "C:\Python27\lib\multiprocessing\managers.py", line 758, in _callmethod
2018-04-03 16:18:03.832000 conn.send((self._id, methodname, args, kwds))
2018-04-03 16:18:03.840000 IOError: [Errno 232] The pipe is being closed
2018-04-03 16:18:03.852000 Process terminated with exit code 1
2018-04-03 16:18:03.860000 Launched python -u C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py
2018-04-03 16:18:03.919000 Main run...
2018-04-03 16:18:03.927000 
2018-04-03 16:18:03.996000 Starting threads...
2018-04-03 16:18:04.012000 try write
2018-04-03 16:18:04.025000 write ok
2018-04-03 16:18:04.036000 Init error
2018-04-03 16:18:14.509000 Launcher terminating...
2018-04-03 16:19:41.880000 Launched python -u C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py
2018-04-03 16:19:41.941000 Main run...
2018-04-03 16:19:41.948000 
2018-04-03 16:19:42.015000 Starting threads...
2018-04-03 16:19:42.030000 try write
2018-04-03 16:19:42.053000 write ok
2018-04-03 16:19:42.064000 Init error
2018-04-03 16:19:44.748000 received: $PUI12,77,15.1,
2018-04-03 16:19:44.771000 
2018-04-03 16:19:44.784000 Wheel to: 15.1
2018-04-03 16:19:44.798000 Traceback (most recent call last):
2018-04-03 16:19:44.804000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 415, in <module>
2018-04-03 16:19:44.810000 while ser.inWaiting():
2018-04-03 16:19:44.818000 AttributeError: 'str' object has no attribute 'inWaiting'
2018-04-03 16:19:44.929000 Process Process-2:
2018-04-03 16:19:44.946000 srv_interpreter_thread start
2018-04-03 16:19:44.965000 
2018-04-03 16:19:44.977000 Accepted new connection
2018-04-03 16:19:44.987000 cmdAgent runCmd by interpreter: $PUI12,77,15.1,
2018-04-03 16:19:44.995000 
2018-04-03 16:19:45.004000 Traceback (most recent call last):
2018-04-03 16:19:45.013000 File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
2018-04-03 16:19:45.022000 self.run()
2018-04-03 16:19:45.030000 File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
2018-04-03 16:19:45.035000 self._target(*self._args, **self._kwargs)
2018-04-03 16:19:45.071000 File "C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py", line 170, in srv_interpreter_thread
2018-04-03 16:19:45.079000 while cmdAgent.hasData() and (flagStopThread.value == 0):
2018-04-03 16:19:45.093000 File "<string>", line 2, in hasData
2018-04-03 16:19:45.099000 File "C:\Python27\lib\multiprocessing\managers.py", line 758, in _callmethod
2018-04-03 16:19:45.106000 conn.send((self._id, methodname, args, kwds))
2018-04-03 16:19:45.113000 IOError: [Errno 232] The pipe is being closed
2018-04-03 16:19:45.119000 Process terminated with exit code 1
2018-04-03 16:19:45.128000 Launched python -u C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py
2018-04-03 16:19:45.191000 Main run...
2018-04-03 16:19:45.203000 
2018-04-03 16:19:45.268000 Starting threads...
2018-04-03 16:19:45.280000 try write
2018-04-03 16:19:45.295000 write ok
2018-04-03 16:19:45.315000 Init error
2018-04-03 16:20:00.454000 Launcher terminating...
2018-04-03 16:20:12.020000 Launched python -u C:\Users\Egor\Desktop\kopter\repository\python_copter\copter_server\main.py
2018-04-03 16:20:12.086000 Main run...
2018-04-03 16:20:12.099000 
2018-04-03 16:20:12.169000 Starting threads...
2018-04-03 16:20:12.186000 try write
2018-04-03 16:20:12.199000 write ok
2018-04-03 16:20:12.222000 Init error
2018-04-03 16:20:15.518000 Launcher terminating...
